// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper1

#include "../ui.h"


void ui_event_comp_IngredientCmp_LeftBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_IngredientCmp = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(comp_IngredientCmp[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI],
                             -1, LV_ANIM_ON);
    }
}
void ui_event_comp_IngredientCmp_RightBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_IngredientCmp = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(comp_IngredientCmp[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI],
                             1, LV_ANIM_ON);
    }
}

// COMPONENT IngredientCmp

lv_obj_t * ui_IngredientCmp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_IngredientCmp;
    cui_IngredientCmp = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_IngredientCmp);
    lv_obj_set_height(cui_IngredientCmp, 72);
    lv_obj_set_width(cui_IngredientCmp, LV_SIZE_CONTENT);   /// 226
    lv_obj_set_x(cui_IngredientCmp, -183);
    lv_obj_set_y(cui_IngredientCmp, -92);
    lv_obj_set_align(cui_IngredientCmp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_IngredientCmp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_IngredientCmp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_IngredientCmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_DoughBallsQtyImg;
    cui_DoughBallsQtyImg = lv_img_create(cui_IngredientCmp);
    lv_img_set_src(cui_DoughBallsQtyImg, &ui_img_3558094_bake_bread_fast_food_pizza_icon_png);
    lv_obj_set_width(cui_DoughBallsQtyImg, 48);
    lv_obj_set_height(cui_DoughBallsQtyImg, 48);
    lv_obj_set_x(cui_DoughBallsQtyImg, -345);
    lv_obj_set_y(cui_DoughBallsQtyImg, -189);
    lv_obj_set_align(cui_DoughBallsQtyImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_DoughBallsQtyImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_DoughBallsQtyImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_MiddleContainer;
    cui_MiddleContainer = lv_obj_create(cui_IngredientCmp);
    lv_obj_remove_style_all(cui_MiddleContainer);
    lv_obj_set_width(cui_MiddleContainer, 333);
    lv_obj_set_height(cui_MiddleContainer, lv_pct(100));
    lv_obj_set_x(cui_MiddleContainer, 1);
    lv_obj_set_y(cui_MiddleContainer, -22);
    lv_obj_set_align(cui_MiddleContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_MiddleContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_MiddleContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_MiddleContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Container13;
    cui_Container13 = lv_obj_create(cui_MiddleContainer);
    lv_obj_remove_style_all(cui_Container13);
    lv_obj_set_width(cui_Container13, lv_pct(100));
    lv_obj_set_height(cui_Container13, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(cui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_IngredientNameCmp;
    cui_IngredientNameCmp = lv_label_create(cui_Container13);
    lv_obj_set_width(cui_IngredientNameCmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_IngredientNameCmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_IngredientNameCmp, -249);
    lv_obj_set_y(cui_IngredientNameCmp, -218);
    lv_obj_set_align(cui_IngredientNameCmp, LV_ALIGN_CENTER);
    lv_label_set_text(cui_IngredientNameCmp, "Dough balls");
    lv_obj_set_style_pad_left(cui_IngredientNameCmp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_IngredientNameCmp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_IngredientNameCmp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_IngredientNameCmp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_IngredientCmpValue;
    cui_IngredientCmpValue = lv_label_create(cui_Container13);
    lv_obj_set_width(cui_IngredientCmpValue, 47);
    lv_obj_set_height(cui_IngredientCmpValue, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(cui_IngredientCmpValue, -287);
    lv_obj_set_y(cui_IngredientCmpValue, -36);
    lv_obj_set_align(cui_IngredientCmpValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_IngredientCmpValue, "");
    lv_obj_set_style_text_align(cui_IngredientCmpValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_IngredientCmpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_IngredientCmpValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_IngredientCmpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_IngredientCmpValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_IngredientCmpContainer;
    cui_IngredientCmpContainer = lv_obj_create(cui_MiddleContainer);
    lv_obj_remove_style_all(cui_IngredientCmpContainer);
    lv_obj_set_height(cui_IngredientCmpContainer, 38);
    lv_obj_set_width(cui_IngredientCmpContainer, lv_pct(100));
    lv_obj_set_x(cui_IngredientCmpContainer, -194);
    lv_obj_set_y(cui_IngredientCmpContainer, -184);
    lv_obj_set_align(cui_IngredientCmpContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_IngredientCmpContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_IngredientCmpContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_IngredientCmpContainer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(cui_IngredientCmpContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_IngredientCmpContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_IngredientCmpContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_IngredientCmpContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_IngredientCmpContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_IngredientCmpSli;
    cui_IngredientCmpSli = lv_slider_create(cui_IngredientCmpContainer);
    lv_slider_set_range(cui_IngredientCmpSli, 100, 1000);
    lv_slider_set_value(cui_IngredientCmpSli, 1000, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_IngredientCmpSli) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_IngredientCmpSli, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_height(cui_IngredientCmpSli, 12);
    lv_obj_set_width(cui_IngredientCmpSli, lv_pct(75));
    lv_obj_set_x(cui_IngredientCmpSli, -242);
    lv_obj_set_y(cui_IngredientCmpSli, -41);
    lv_obj_set_align(cui_IngredientCmpSli, LV_ALIGN_CENTER);

    lv_obj_t * cui_Container5;
    cui_Container5 = lv_obj_create(cui_IngredientCmpContainer);
    lv_obj_remove_style_all(cui_Container5);
    lv_obj_set_width(cui_Container5, 15);
    lv_obj_set_height(cui_Container5, 50);
    lv_obj_set_align(cui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LeftBtn;
    cui_LeftBtn = lv_btn_create(cui_IngredientCmpContainer);
    lv_obj_set_width(cui_LeftBtn, 30);
    lv_obj_set_height(cui_LeftBtn, 30);
    lv_obj_set_align(cui_LeftBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_LeftBtn, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_LeftBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label12;
    cui_Label12 = lv_label_create(cui_LeftBtn);
    lv_obj_set_width(cui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label12, "-");

    lv_obj_t * cui_RightBtn;
    cui_RightBtn = lv_btn_create(cui_IngredientCmpContainer);
    lv_obj_set_width(cui_RightBtn, 30);
    lv_obj_set_height(cui_RightBtn, 30);
    lv_obj_set_align(cui_RightBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_RightBtn, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_RightBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label13;
    cui_Label13 = lv_label_create(cui_RightBtn);
    lv_obj_set_width(cui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label13, "+");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_INGREDIENTCMP_NUM);
    children[UI_COMP_INGREDIENTCMP_INGREDIENTCMP] = cui_IngredientCmp;
    children[UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG] = cui_DoughBallsQtyImg;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER] = cui_MiddleContainer;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13] = cui_Container13;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP] = cui_IngredientNameCmp;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTCMPVALUE] = cui_IngredientCmpValue;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER] = cui_IngredientCmpContainer;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI] = cui_IngredientCmpSli;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_CONTAINER5] = cui_Container5;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_LEFTBTN] = cui_LeftBtn;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_LEFTBTN_LABEL12] = cui_Label12;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_RIGHTBTN] = cui_RightBtn;
    children[UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_RIGHTBTN_LABEL13] = cui_Label13;
    lv_obj_add_event_cb(cui_IngredientCmp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_IngredientCmp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_LeftBtn, ui_event_comp_IngredientCmp_LeftBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_RightBtn, ui_event_comp_IngredientCmp_RightBtn, LV_EVENT_ALL, children);
    ui_comp_IngredientCmp_create_hook(cui_IngredientCmp);
    return cui_IngredientCmp;
}

