// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#ifndef _PIZZAHELPER_UI_H
#define _PIZZAHELPER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_PizzaType
void ui_PizzaType_screen_init(void);
extern lv_obj_t * ui_PizzaType;
extern lv_obj_t * ui_MainContainer;
extern lv_obj_t * ui_RoundPnl;
extern lv_obj_t * ui_PizzaTypeImg;
extern lv_obj_t * ui_PizzaTypeLbl;
extern lv_obj_t * ui_GrandmaPnl;
extern lv_obj_t * ui_PizzaTypeImg1;
extern lv_obj_t * ui_PizzaTypeLbl1;
extern lv_obj_t * ui_FocacciaPnl;
extern lv_obj_t * ui_PizzaTypeImg2;
extern lv_obj_t * ui_PizzaTypeLbl2;
extern lv_obj_t * ui_DetroitPnl;
extern lv_obj_t * ui_PizzaTypeImg3;
extern lv_obj_t * ui_PizzaTypeLbl3;
extern lv_obj_t * ui_BreadPnl;
extern lv_obj_t * ui_PizzaTypeImg4;
extern lv_obj_t * ui_PizzaTypeLbl4;
// SCREEN: ui_Method
void ui_Method_screen_init(void);
extern lv_obj_t * ui_Method;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_DirectPnl;
extern lv_obj_t * ui_PizzaTypeImg6;
extern lv_obj_t * ui_PizzaTypeLbl6;
extern lv_obj_t * ui_BigaPnl;
extern lv_obj_t * ui_PizzaTypeImg5;
extern lv_obj_t * ui_PizzaTypeLbl5;
extern lv_obj_t * ui_PoolishPnl;
extern lv_obj_t * ui_PizzaTypeImg7;
extern lv_obj_t * ui_PizzaTypeLbl7;
extern lv_obj_t * ui_BigaPolishPnl;
extern lv_obj_t * ui_PizzaTypeImg8;
extern lv_obj_t * ui_PizzaTypeLbl8;
// SCREEN: ui_Yeast
void ui_Yeast_screen_init(void);
extern lv_obj_t * ui_Yeast;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_YeastFreshPnl;
extern lv_obj_t * ui_YeastImg;
extern lv_obj_t * ui_YeastLbl;
extern lv_obj_t * ui_YeastDryPnl;
extern lv_obj_t * ui_YeastImg1;
extern lv_obj_t * ui_YeastLbl1;
extern lv_obj_t * ui_YeastSourdoughPnl;
extern lv_obj_t * ui_YeastImg2;
extern lv_obj_t * ui_YeastLbl2;
// SCREEN: ui_Ingredients
void ui_Ingredients_screen_init(void);
void ui_event_Ingredients(lv_event_t * e);
extern lv_obj_t * ui_Ingredients;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_WaterCmp;
extern lv_obj_t * ui_LeaveningCmp;
extern lv_obj_t * ui_RoomTempCmp;
extern lv_obj_t * ui_DoughballWeightCmp;
extern lv_obj_t * ui_DoughballQtyCmp;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_FlourQ;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_WaterQ;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_YeastQ;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_SaltQ;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_OilQ;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_pizza_png);    // assets\pizza.png
LV_IMG_DECLARE(ui_img_grandma_png);    // assets\grandma.png
LV_IMG_DECLARE(ui_img_direct_png);    // assets\direct.png
LV_IMG_DECLARE(ui_img_biga_png);    // assets\biga.png
LV_IMG_DECLARE(ui_img_poolish_png);    // assets\poolish.png
LV_IMG_DECLARE(ui_img_fresh_png);    // assets\fresh.png
LV_IMG_DECLARE(ui_img_dry_png);    // assets\dry.png
LV_IMG_DECLARE(ui_img_sourdough_png);    // assets\sourdough.png
LV_IMG_DECLARE(
    ui_img_3558094_bake_bread_fast_food_pizza_icon_png);    // assets\3558094_bake_bread_fast_food_pizza_icon.png
LV_IMG_DECLARE(
    ui_img_2995004_rain_water_drop_weather_cloud_icon_png);    // assets\2995004_rain_water_drop_weather_cloud_icon.png
LV_IMG_DECLARE(
    ui_img_2824441_clock_stopwatch_time_timer_icon_png);    // assets\2824441_clock_stopwatch_time_timer_icon.png
LV_IMG_DECLARE(
    ui_img_3856401_celsius_degrees_temperature_thermometer_weather_icon_png);    // assets\3856401_celsius_degrees_temperature_thermometer_weather_icon.png
LV_IMG_DECLARE(
    ui_img_7450398_kitchen_utensils_scale_appliance_weight_icon_png);    // assets\7450398_kitchen_utensils_scale_appliance_weight_icon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
