// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_DoughballsCntExt_create_hook(lv_obj_t * comp)
{
}
