// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PreIngredients
void ui_PreIngredients_screen_init(void);
lv_obj_t *ui_PreIngredients;
lv_obj_t *ui_Container9;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_WaterCmp;
lv_obj_t *ui_RoomTempCmp;
lv_obj_t *ui_LeaveningCmp;
lv_obj_t *ui_Container8;
lv_obj_t *ui_Image1;
lv_obj_t *ui_UseTheFridgeSw;
lv_obj_t *ui_Label21;
lv_obj_t *ui_StarterReadyLbl;
lv_obj_t *ui_PizzaReadyLbl;
lv_obj_t *ui_BtnNext;
lv_obj_t *ui_Label1;
lv_obj_t *ui_BtnPrev;
lv_obj_t *ui_Label14;
lv_obj_t *ui_TopBar;
lv_obj_t *ui_HomeImg;

// SCREEN: ui_Ingredients
void ui_Ingredients_screen_init(void);
lv_obj_t *ui_Ingredients;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_PrefWaterCmp;
lv_obj_t *ui_PrefPercCmp;
lv_obj_t *ui_DoughballWeightCmp;
lv_obj_t *ui_DoughballQtyCmp;
lv_obj_t *ui_PanelIngredients;
lv_obj_t *ui_IngrStarterLbl;
lv_obj_t *ui_PrefPnl;
lv_obj_t *ui_PrefLEft;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label19;
lv_obj_t *ui_PrefCent;
lv_obj_t *ui_FlourB;
lv_obj_t *ui_WaterB;
lv_obj_t *ui_YeastB;
lv_obj_t *ui_PrefRight;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label20;
lv_obj_t *ui_IngrLbl;
lv_obj_t *ui_IngrLbl2;
lv_obj_t *ui_IngrPanel;
lv_obj_t *ui_IngrLEft;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label10;
lv_obj_t *ui_IngrCent;
lv_obj_t *ui_FlourQ;
lv_obj_t *ui_WaterQ;
lv_obj_t *ui_YeastQ;
lv_obj_t *ui_SaltQ;
lv_obj_t *ui_OilQ;
lv_obj_t *ui_IngrRight;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label11;
lv_obj_t *ui_BtnPrev2;
lv_obj_t *ui_Label22;
lv_obj_t *ui_BtnNextIngredients;
lv_obj_t *ui_Label24;
lv_obj_t *ui_TopBar2;
lv_obj_t *ui_HomeImg2;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
