// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper1

#ifndef _PIZZAHELPER1_UI_H
#define _PIZZAHELPER1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_PreIngredients
void ui_PreIngredients_screen_init(void);
extern lv_obj_t * ui_PreIngredients;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_WaterCmp;
extern lv_obj_t * ui_RoomTempCmp;
extern lv_obj_t * ui_LeaveningCmp;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_UseTheFridgeSw;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_StarterReadyLbl;
extern lv_obj_t * ui_PizzaReadyLbl;
extern lv_obj_t * ui_BtnNext;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_BtnPrev;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TopBar;
extern lv_obj_t * ui_HomeImg;
// SCREEN: ui_Ingredients
void ui_Ingredients_screen_init(void);
extern lv_obj_t * ui_Ingredients;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_PrefWaterCmp;
extern lv_obj_t * ui_PrefPercCmp;
extern lv_obj_t * ui_DoughballWeightCmp;
extern lv_obj_t * ui_DoughballQtyCmp;
extern lv_obj_t * ui_PanelIngredients;
extern lv_obj_t * ui_IngrStarterLbl;
extern lv_obj_t * ui_PrefPnl;
extern lv_obj_t * ui_PrefLEft;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_PrefCent;
extern lv_obj_t * ui_FlourB;
extern lv_obj_t * ui_WaterB;
extern lv_obj_t * ui_YeastB;
extern lv_obj_t * ui_PrefRight;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_IngrLbl;
extern lv_obj_t * ui_IngrLbl2;
extern lv_obj_t * ui_IngrPanel;
extern lv_obj_t * ui_IngrLEft;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_IngrCent;
extern lv_obj_t * ui_FlourQ;
extern lv_obj_t * ui_WaterQ;
extern lv_obj_t * ui_YeastQ;
extern lv_obj_t * ui_SaltQ;
extern lv_obj_t * ui_OilQ;
extern lv_obj_t * ui_IngrRight;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_BtnPrev2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_BtnNextIngredients;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_TopBar2;
extern lv_obj_t * ui_HomeImg2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_pizza_back01_png);    // assets\pizza_back01.png
LV_IMG_DECLARE(
    ui_img_3558094_bake_bread_fast_food_pizza_icon_png);    // assets\3558094_bake_bread_fast_food_pizza_icon.png
LV_IMG_DECLARE(
    ui_img_2995004_rain_water_drop_weather_cloud_icon_png);    // assets\2995004_rain_water_drop_weather_cloud_icon.png
LV_IMG_DECLARE(
    ui_img_3856401_celsius_degrees_temperature_thermometer_weather_icon_png);    // assets\3856401_celsius_degrees_temperature_thermometer_weather_icon.png
LV_IMG_DECLARE(
    ui_img_2824441_clock_stopwatch_time_timer_icon_png);    // assets\2824441_clock_stopwatch_time_timer_icon.png
LV_IMG_DECLARE(
    ui_img_10673486_fridge_kitchen_refrigerator_food_and_icon_png);    // assets\10673486_fridge_kitchen_refrigerator_food_and_icon.png
LV_IMG_DECLARE(ui_img_8726048_home_icon_png);    // assets\8726048_home_icon.png
LV_IMG_DECLARE(
    ui_img_7450398_kitchen_utensils_scale_appliance_weight_icon_png);    // assets\7450398_kitchen_utensils_scale_appliance_weight_icon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
