// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Components_screen_init(void)
{
    ui_Components = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Components, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTimeline2 = lv_obj_create(ui_Components);
    lv_obj_set_width(ui_PanelTimeline2, 714);
    lv_obj_set_height(ui_PanelTimeline2, 368);
    lv_obj_set_x(ui_PanelTimeline2, 0);
    lv_obj_set_y(ui_PanelTimeline2, -18);
    lv_obj_set_align(ui_PanelTimeline2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTimeline2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelTimeline2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTimeline2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimelineCnt = lv_obj_create(ui_PanelTimeline2);
    lv_obj_remove_style_all(ui_TimelineCnt);
    lv_obj_set_height(ui_TimelineCnt, 40);
    lv_obj_set_width(ui_TimelineCnt, lv_pct(100));
    lv_obj_set_align(ui_TimelineCnt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TimelineCnt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TimelineCnt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimelineCnt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_TimelineCnt, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TimelineCnt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TimelineCnt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TimelineCnt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimelineCbx = lv_checkbox_create(ui_TimelineCnt);
    lv_checkbox_set_text(ui_TimelineCbx, "test");
    lv_obj_set_width(ui_TimelineCbx, lv_pct(100));
    lv_obj_set_height(ui_TimelineCbx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimelineCbx, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimelineCbx, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


}
