// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Ingredients_screen_init(void)
{
    ui_Ingredients = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ingredients, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
