// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Oven_screen_init(void)
{
    ui_Oven = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Oven, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Oven);
    lv_obj_set_width(ui_Arc1, 276);
    lv_obj_set_height(ui_Arc1, 271);
    lv_obj_set_x(ui_Arc1, -195);
    lv_obj_set_y(ui_Arc1, -44);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 500);


    ui_Slider1 = lv_slider_create(ui_Oven);
    lv_obj_set_width(ui_Slider1, 264);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -196);
    lv_obj_set_y(ui_Slider1, 115);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);



}
