// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Timeline_screen_init(void)
{
    ui_Timeline = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Timeline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnPrev3 = lv_btn_create(ui_Timeline);
    lv_obj_set_width(ui_BtnPrev3, 100);
    lv_obj_set_height(ui_BtnPrev3, 50);
    lv_obj_set_x(ui_BtnPrev3, -340);
    lv_obj_set_y(ui_BtnPrev3, 204);
    lv_obj_set_align(ui_BtnPrev3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPrev3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrev3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrevLbl3 = lv_label_create(ui_BtnPrev3);
    lv_obj_set_width(ui_PrevLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrevLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrevLbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrevLbl3, "PREV");

    ui_PanelTimeline = lv_obj_create(ui_Timeline);
    lv_obj_set_width(ui_PanelTimeline, 714);
    lv_obj_set_height(ui_PanelTimeline, 368);
    lv_obj_set_x(ui_PanelTimeline, 0);
    lv_obj_set_y(ui_PanelTimeline, -18);
    lv_obj_set_align(ui_PanelTimeline, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTimeline, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelTimeline, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTimeline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimelineCnt = lv_obj_create(ui_PanelTimeline);
    lv_obj_remove_style_all(ui_TimelineCnt);
    lv_obj_set_height(ui_TimelineCnt, 40);
    lv_obj_set_width(ui_TimelineCnt, lv_pct(100));
    lv_obj_set_align(ui_TimelineCnt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TimelineCnt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TimelineCnt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimelineCnt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_TimelineCnt);
    lv_obj_set_width(ui_Checkbox1, lv_pct(100));
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_BtnPrev3, ui_event_BtnPrev3, LV_EVENT_ALL, NULL);

}
