// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_ToppingHelper_screen_init(void)
{
    ui_ToppingHelper = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ToppingHelper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToppingCnt = lv_obj_create(ui_ToppingHelper);
    lv_obj_remove_style_all(ui_ToppingCnt);
    lv_obj_set_width(ui_ToppingCnt, lv_pct(100));
    lv_obj_set_height(ui_ToppingCnt, lv_pct(100));
    lv_obj_set_align(ui_ToppingCnt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ToppingCnt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ToppingCnt, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ToppingCnt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ToppingCnt, &ui_img_pizza_back01_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ToppingCnt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ToppingCnt, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopContainer = lv_obj_create(ui_ToppingHelper);
    lv_obj_remove_style_all(ui_TopContainer);
    lv_obj_set_height(ui_TopContainer, 168);
    lv_obj_set_width(ui_TopContainer, lv_pct(100));
    lv_obj_set_align(ui_TopContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IngredientText = lv_textarea_create(ui_TopContainer);
    lv_obj_set_width(ui_IngredientText, lv_pct(90));
    lv_obj_set_height(ui_IngredientText, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_IngredientText, 0);
    lv_obj_set_y(ui_IngredientText, -30);
    lv_obj_set_align(ui_IngredientText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_IngredientText, "Ingredients...");
    lv_textarea_set_one_line(ui_IngredientText, true);



    ui_Image1 = lv_img_create(ui_TopContainer);
    lv_img_set_src(ui_Image1, &ui_img_9921876_spoon_fork_kitchen_restaurant_utensil_icon_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -332);
    lv_obj_set_y(ui_Image1, 35);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AvailableIngredientsPanel = lv_obj_create(ui_TopContainer);
    lv_obj_set_width(ui_AvailableIngredientsPanel, 636);
    lv_obj_set_height(ui_AvailableIngredientsPanel, 67);
    lv_obj_set_x(ui_AvailableIngredientsPanel, 42);
    lv_obj_set_y(ui_AvailableIngredientsPanel, 34);
    lv_obj_set_align(ui_AvailableIngredientsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AvailableIngredientsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AvailableIngredientsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_AvailableIngredientsPanel, LV_DIR_HOR);

    ui_IngredientsKeyboard = lv_keyboard_create(ui_ToppingHelper);
    lv_obj_set_width(ui_IngredientsKeyboard, 758);
    lv_obj_set_height(ui_IngredientsKeyboard, 244);
    lv_obj_set_x(ui_IngredientsKeyboard, -1);
    lv_obj_set_y(ui_IngredientsKeyboard, 102);
    lv_obj_set_align(ui_IngredientsKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_IngredientsSuggestionPanel = lv_obj_create(ui_ToppingHelper);
    lv_obj_set_width(ui_IngredientsSuggestionPanel, 236);
    lv_obj_set_height(ui_IngredientsSuggestionPanel, 149);
    lv_obj_set_x(ui_IngredientsSuggestionPanel, -240);
    lv_obj_set_y(ui_IngredientsSuggestionPanel, -86);
    lv_obj_set_align(ui_IngredientsSuggestionPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IngredientsSuggestionPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_IngredientsSuggestionPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsSuggestionPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_BtnGetRecipes = lv_btn_create(ui_ToppingHelper);
    lv_obj_set_width(ui_BtnGetRecipes, 109);
    lv_obj_set_height(ui_BtnGetRecipes, 50);
    lv_obj_set_x(ui_BtnGetRecipes, 334);
    lv_obj_set_y(ui_BtnGetRecipes, 205);
    lv_obj_set_align(ui_BtnGetRecipes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGetRecipes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGetRecipes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrevLbl4 = lv_label_create(ui_BtnGetRecipes);
    lv_obj_set_width(ui_PrevLbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrevLbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrevLbl4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrevLbl4, "GET RECIPES");

    lv_obj_add_event_cb(ui_IngredientText, ui_event_IngredientText, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_IngredientsKeyboard, ui_IngredientText);

}
