// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Yeast_screen_init(void)
{
    ui_Yeast = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Yeast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Yeast);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container1, &ui_img_pizza_back01_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YeastFreshPnl = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_YeastFreshPnl, 144);
    lv_obj_set_height(ui_YeastFreshPnl, 149);
    lv_obj_set_x(ui_YeastFreshPnl, -245);
    lv_obj_set_y(ui_YeastFreshPnl, -157);
    lv_obj_set_align(ui_YeastFreshPnl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_YeastFreshPnl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_YeastFreshPnl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_YeastFreshPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YeastFreshPnl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YeastFreshPnl, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YeastImg = lv_img_create(ui_YeastFreshPnl);
    lv_img_set_src(ui_YeastImg, &ui_img_fresh_png);
    lv_obj_set_width(ui_YeastImg, 100);
    lv_obj_set_height(ui_YeastImg, 98);
    lv_obj_set_align(ui_YeastImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YeastImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_YeastImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_YeastLbl = lv_label_create(ui_YeastFreshPnl);
    lv_obj_set_width(ui_YeastLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YeastLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_YeastLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YeastLbl, "Fresh");

    ui_YeastDryPnl = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_YeastDryPnl, 144);
    lv_obj_set_height(ui_YeastDryPnl, 149);
    lv_obj_set_x(ui_YeastDryPnl, -245);
    lv_obj_set_y(ui_YeastDryPnl, -157);
    lv_obj_set_align(ui_YeastDryPnl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_YeastDryPnl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_YeastDryPnl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_YeastDryPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YeastDryPnl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YeastDryPnl, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YeastImg1 = lv_img_create(ui_YeastDryPnl);
    lv_img_set_src(ui_YeastImg1, &ui_img_dry_png);
    lv_obj_set_width(ui_YeastImg1, 100);
    lv_obj_set_height(ui_YeastImg1, 98);
    lv_obj_set_align(ui_YeastImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YeastImg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_YeastImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_YeastLbl1 = lv_label_create(ui_YeastDryPnl);
    lv_obj_set_width(ui_YeastLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YeastLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_YeastLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YeastLbl1, "Dry");

    ui_YeastSourdoughPnl = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_YeastSourdoughPnl, 144);
    lv_obj_set_height(ui_YeastSourdoughPnl, 149);
    lv_obj_set_x(ui_YeastSourdoughPnl, -245);
    lv_obj_set_y(ui_YeastSourdoughPnl, -157);
    lv_obj_set_align(ui_YeastSourdoughPnl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_YeastSourdoughPnl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_YeastSourdoughPnl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_YeastSourdoughPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YeastSourdoughPnl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YeastSourdoughPnl, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YeastImg2 = lv_img_create(ui_YeastSourdoughPnl);
    lv_img_set_src(ui_YeastImg2, &ui_img_sourdough_png);
    lv_obj_set_width(ui_YeastImg2, 100);
    lv_obj_set_height(ui_YeastImg2, 98);
    lv_obj_set_align(ui_YeastImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YeastImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_YeastImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_YeastLbl2 = lv_label_create(ui_YeastSourdoughPnl);
    lv_obj_set_width(ui_YeastLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YeastLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_YeastLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YeastLbl2, "Sourdough");

    ui_BtnPrev2 = lv_btn_create(ui_Yeast);
    lv_obj_set_width(ui_BtnPrev2, 100);
    lv_obj_set_height(ui_BtnPrev2, 50);
    lv_obj_set_x(ui_BtnPrev2, -340);
    lv_obj_set_y(ui_BtnPrev2, 204);
    lv_obj_set_align(ui_BtnPrev2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPrev2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrev2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrevLbl2 = lv_label_create(ui_BtnPrev2);
    lv_obj_set_width(ui_PrevLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrevLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrevLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrevLbl2, "PREV");

    ui_TopBar3 = lv_obj_create(ui_Yeast);
    lv_obj_remove_style_all(ui_TopBar3);
    lv_obj_set_height(ui_TopBar3, 36);
    lv_obj_set_width(ui_TopBar3, lv_pct(100));
    lv_obj_set_align(ui_TopBar3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_TopBar3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn3 = lv_img_create(ui_TopBar3);
    lv_img_set_src(ui_HomeBtn3, &ui_img_8726048_home_icon_png);
    lv_obj_set_width(ui_HomeBtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBtn3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnPrev2, ui_event_BtnPrev2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn3, ui_event_HomeBtn3, LV_EVENT_ALL, NULL);

}
