// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper1

#include "../ui.h"

void ui_PreIngredients_screen_init(void)
{
    ui_PreIngredients = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PreIngredients, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_PreIngredients);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container9, &ui_img_pizza_back01_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel1, 512);
    lv_obj_set_height(ui_Panel1, 449);
    lv_obj_set_x(ui_Panel1, 6);
    lv_obj_set_y(ui_Panel1, -34);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterCmp = ui_IngredientCmp_create(ui_Panel1);
    lv_obj_set_x(ui_WaterCmp, -168);
    lv_obj_set_y(ui_WaterCmp, -169);

    lv_img_set_src(ui_comp_get_child(ui_WaterCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_2995004_rain_water_drop_weather_cloud_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_WaterCmp, UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP),
                      "Water percentage of the final dough");



    lv_slider_set_range(ui_comp_get_child(ui_WaterCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 60, 100);





    ui_RoomTempCmp = ui_IngredientCmp_create(ui_Panel1);
    lv_obj_set_x(ui_RoomTempCmp, -172);
    lv_obj_set_y(ui_RoomTempCmp, -81);

    lv_img_set_src(ui_comp_get_child(ui_RoomTempCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_3856401_celsius_degrees_temperature_thermometer_weather_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_RoomTempCmp,
                                        UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP), "Temperature of your room");



    lv_slider_set_range(ui_comp_get_child(ui_RoomTempCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 0, 45);





    ui_LeaveningCmp = ui_IngredientCmp_create(ui_Panel1);
    lv_obj_set_x(ui_LeaveningCmp, -170);
    lv_obj_set_y(ui_LeaveningCmp, 10);

    lv_img_set_src(ui_comp_get_child(ui_LeaveningCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_2824441_clock_stopwatch_time_timer_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_LeaveningCmp,
                                        UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP), "Total leavening time");



    lv_slider_set_range(ui_comp_get_child(ui_LeaveningCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 4, 72);





    ui_Container8 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 382);
    lv_obj_set_height(ui_Container8, 69);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_Image1, &ui_img_10673486_fridge_kitchen_refrigerator_food_and_icon_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UseTheFridgeSw = lv_switch_create(ui_Container8);
    lv_obj_set_width(ui_UseTheFridgeSw, 50);
    lv_obj_set_height(ui_UseTheFridgeSw, 25);
    lv_obj_set_x(ui_UseTheFridgeSw, -102);
    lv_obj_set_y(ui_UseTheFridgeSw, -2);
    lv_obj_set_align(ui_UseTheFridgeSw, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_UseTheFridgeSw, lv_color_hex(0x2A2A2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UseTheFridgeSw, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container8);
    lv_obj_set_height(ui_Label21, 22);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label21, -12);
    lv_obj_set_y(ui_Label21, -2);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Use the fridge");
    lv_obj_set_style_pad_left(ui_Label21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label21, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StarterReadyLbl = lv_label_create(ui_Panel1);
    lv_obj_set_height(ui_StarterReadyLbl, 31);
    lv_obj_set_width(ui_StarterReadyLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_StarterReadyLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StarterReadyLbl, "Biga ready at: ");
    lv_obj_set_style_pad_left(ui_StarterReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StarterReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StarterReadyLbl, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StarterReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PizzaReadyLbl = lv_label_create(ui_Panel1);
    lv_obj_set_height(ui_PizzaReadyLbl, 31);
    lv_obj_set_width(ui_PizzaReadyLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_PizzaReadyLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PizzaReadyLbl, "Pizza ready to bake at: ");
    lv_obj_set_style_pad_left(ui_PizzaReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PizzaReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PizzaReadyLbl, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PizzaReadyLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNext = lv_btn_create(ui_PreIngredients);
    lv_obj_set_width(ui_BtnNext, 100);
    lv_obj_set_height(ui_BtnNext, 50);
    lv_obj_set_x(ui_BtnNext, 332);
    lv_obj_set_y(ui_BtnNext, 198);
    lv_obj_set_align(ui_BtnNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_BtnNext);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "NEXT");

    ui_BtnPrev = lv_btn_create(ui_PreIngredients);
    lv_obj_set_width(ui_BtnPrev, 100);
    lv_obj_set_height(ui_BtnPrev, 50);
    lv_obj_set_x(ui_BtnPrev, -333);
    lv_obj_set_y(ui_BtnPrev, 199);
    lv_obj_set_align(ui_BtnPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_BtnPrev);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PREV");

}
