// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper1

#include "../ui.h"

void ui_PreIngredients_screen_init(void)
{
    ui_PreIngredients = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PreIngredients, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_PreIngredients);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WaterCmp = ui_IngredientCmp_create(ui_Container9);
    lv_obj_set_x(ui_WaterCmp, -168);
    lv_obj_set_y(ui_WaterCmp, -169);

    lv_img_set_src(ui_comp_get_child(ui_WaterCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_2995004_rain_water_drop_weather_cloud_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_WaterCmp, UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP),
                      "Water");



    lv_slider_set_range(ui_comp_get_child(ui_WaterCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 60, 100);






    ui_RoomTempCmp = ui_IngredientCmp_create(ui_Container9);
    lv_obj_set_x(ui_RoomTempCmp, -172);
    lv_obj_set_y(ui_RoomTempCmp, -81);

    lv_img_set_src(ui_comp_get_child(ui_RoomTempCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_3856401_celsius_degrees_temperature_thermometer_weather_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_RoomTempCmp,
                                        UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP), "Temperature");



    lv_slider_set_range(ui_comp_get_child(ui_RoomTempCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 0, 45);






    ui_LeaveningCmp = ui_IngredientCmp_create(ui_Container9);
    lv_obj_set_x(ui_LeaveningCmp, -170);
    lv_obj_set_y(ui_LeaveningCmp, 10);

    lv_img_set_src(ui_comp_get_child(ui_LeaveningCmp, UI_COMP_INGREDIENTCMP_DOUGHBALLSQTYIMG),
                   &ui_img_2824441_clock_stopwatch_time_timer_icon_png);



    lv_label_set_text(ui_comp_get_child(ui_LeaveningCmp,
                                        UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_CONTAINER13_INGREDIENTNAMECMP), "Levening time");



    lv_slider_set_range(ui_comp_get_child(ui_LeaveningCmp,
                                          UI_COMP_INGREDIENTCMP_MIDDLECONTAINER_INGREDIENTCMPCONTAINER_INGREDIENTCMPSLI), 4, 72);






    ui_BtnNext = lv_btn_create(ui_PreIngredients);
    lv_obj_set_width(ui_BtnNext, 100);
    lv_obj_set_height(ui_BtnNext, 50);
    lv_obj_set_x(ui_BtnNext, 332);
    lv_obj_set_y(ui_BtnNext, 198);
    lv_obj_set_align(ui_BtnNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_BtnNext);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "NEXT");

    ui_BtnPrev = lv_btn_create(ui_PreIngredients);
    lv_obj_set_width(ui_BtnPrev, 100);
    lv_obj_set_height(ui_BtnPrev, 50);
    lv_obj_set_x(ui_BtnPrev, -333);
    lv_obj_set_y(ui_BtnPrev, 199);
    lv_obj_set_align(ui_BtnPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_BtnPrev);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PREV");

}
