// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Ingredients_screen_init(void)
{
    ui_Ingredients = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ingredients, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_Ingredients);
    lv_roller_set_options(ui_Roller1, "Dried\nFresh\nSourdough", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 99);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 221);
    lv_obj_set_y(ui_Roller1, 57);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Container4 = lv_obj_create(ui_Ingredients);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoughballsCntExt4 = ui_DoughballsCntExt_create(ui_Container4);
    lv_obj_set_x(ui_DoughballsCntExt4, -184);
    lv_obj_set_y(ui_DoughballsCntExt4, 97);

    lv_img_set_src(ui_comp_get_child(ui_DoughballsCntExt4, UI_COMP_DOUGHBALLSCNTEXT_DOUGHBALLSQTYIMG),
                   &ui_img_2995004_rain_water_drop_weather_cloud_icon_png);


    lv_label_set_text(ui_comp_get_child(ui_DoughballsCntExt4, UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_LABEL1),
                      "Water percentage");



    lv_slider_set_range(ui_comp_get_child(ui_DoughballsCntExt4,
                                          UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_DOUGHBALLSQTYCNT_DOUGHBALLSQTYSLI), 50, 100);


    ui_DoughballsCntExt3 = ui_DoughballsCntExt_create(ui_Container4);
    lv_obj_set_x(ui_DoughballsCntExt3, -186);
    lv_obj_set_y(ui_DoughballsCntExt3, 190);

    lv_img_set_src(ui_comp_get_child(ui_DoughballsCntExt3, UI_COMP_DOUGHBALLSCNTEXT_DOUGHBALLSQTYIMG),
                   &ui_img_2824441_clock_stopwatch_time_timer_icon_png);


    lv_label_set_text(ui_comp_get_child(ui_DoughballsCntExt3, UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_LABEL1),
                      "Livening time");



    lv_slider_set_range(ui_comp_get_child(ui_DoughballsCntExt3,
                                          UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_DOUGHBALLSQTYCNT_DOUGHBALLSQTYSLI), 2, 50);


    ui_DoughballsCntExt2 = ui_DoughballsCntExt_create(ui_Container4);
    lv_obj_set_x(ui_DoughballsCntExt2, -182);
    lv_obj_set_y(ui_DoughballsCntExt2, 1);

    lv_img_set_src(ui_comp_get_child(ui_DoughballsCntExt2, UI_COMP_DOUGHBALLSCNTEXT_DOUGHBALLSQTYIMG),
                   &ui_img_3856401_celsius_degrees_temperature_thermometer_weather_icon_png);


    lv_label_set_text(ui_comp_get_child(ui_DoughballsCntExt2, UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_LABEL1),
                      "Room temperature");



    lv_slider_set_range(ui_comp_get_child(ui_DoughballsCntExt2,
                                          UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_DOUGHBALLSQTYCNT_DOUGHBALLSQTYSLI), 0, 50);


    ui_DoughballsCntExt1 = ui_DoughballsCntExt_create(ui_Container4);
    lv_obj_set_x(ui_DoughballsCntExt1, -183);
    lv_obj_set_y(ui_DoughballsCntExt1, -92);

    lv_img_set_src(ui_comp_get_child(ui_DoughballsCntExt1, UI_COMP_DOUGHBALLSCNTEXT_DOUGHBALLSQTYIMG),
                   &ui_img_7450398_kitchen_utensils_scale_appliance_weight_icon_png);


    lv_label_set_text(ui_comp_get_child(ui_DoughballsCntExt1, UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_LABEL1),
                      "Dough ball weight");





    ui_DoughballsCntExt = ui_DoughballsCntExt_create(ui_Container4);
    lv_obj_set_x(ui_DoughballsCntExt, -182);
    lv_obj_set_y(ui_DoughballsCntExt, -181);



    lv_label_set_text(ui_comp_get_child(ui_DoughballsCntExt, UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_LABEL1),
                      "Dough balls quantity");



    lv_slider_set_range(ui_comp_get_child(ui_DoughballsCntExt,
                                          UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_DOUGHBALLSQTYCNT_DOUGHBALLSQTYSLI), 1, 100);
    lv_slider_set_mode(ui_comp_get_child(ui_DoughballsCntExt,
                                         UI_COMP_DOUGHBALLSCNTEXT_MIDDLECONTAINER_DOUGHBALLSQTYCNT_DOUGHBALLSQTYSLI), LV_SLIDER_MODE_NORMAL);



}
