// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: PizzaHelper

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 442);
    lv_obj_set_height(ui_Panel1, 142);
    lv_obj_set_x(ui_Panel1, 9);
    lv_obj_set_y(ui_Panel1, -138);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DoughBallsTa = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_DoughBallsTa, 118);
    lv_obj_set_height(ui_DoughBallsTa, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_DoughBallsTa, -302);
    lv_obj_set_y(ui_DoughBallsTa, -190);
    lv_obj_set_align(ui_DoughBallsTa, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_DoughBallsTa, "Dough balls");
    lv_textarea_set_one_line(ui_DoughBallsTa, true);



    ui_BallWieghtTa = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_BallWieghtTa, 123);
    lv_obj_set_height(ui_BallWieghtTa, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_BallWieghtTa, -301);
    lv_obj_set_y(ui_BallWieghtTa, -136);
    lv_obj_set_align(ui_BallWieghtTa, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_BallWieghtTa, "Ball Weight");
    lv_textarea_set_one_line(ui_BallWieghtTa, true);



    ui_WaterTa = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_WaterTa, 117);
    lv_obj_set_height(ui_WaterTa, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_WaterTa, -301);
    lv_obj_set_y(ui_WaterTa, -136);
    lv_obj_set_align(ui_WaterTa, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WaterTa, "Water %");
    lv_textarea_set_one_line(ui_WaterTa, true);



    ui_LeaveningTimeTa = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_LeaveningTimeTa, 185);
    lv_obj_set_height(ui_LeaveningTimeTa, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_LeaveningTimeTa, -301);
    lv_obj_set_y(ui_LeaveningTimeTa, -136);
    lv_obj_set_align(ui_LeaveningTimeTa, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LeaveningTimeTa, "Leavening Time");
    lv_textarea_set_one_line(ui_LeaveningTimeTa, true);
    lv_textarea_set_password_mode(ui_LeaveningTimeTa, true);
    lv_obj_add_flag(ui_LeaveningTimeTa, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags



    ui_RoomTemperatureTa = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_RoomTemperatureTa, 191);
    lv_obj_set_height(ui_RoomTemperatureTa, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_RoomTemperatureTa, -301);
    lv_obj_set_y(ui_RoomTemperatureTa, -136);
    lv_obj_set_align(ui_RoomTemperatureTa, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RoomTemperatureTa, "Room Temperature");
    lv_textarea_set_one_line(ui_RoomTemperatureTa, true);



    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 405);
    lv_obj_set_height(ui_Keyboard1, 219);
    lv_obj_set_x(ui_Keyboard1, 5);
    lv_obj_set_y(ui_Keyboard1, 114);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller1, "Dried\nFresh\nSourdough", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 309);
    lv_obj_set_y(ui_Roller1, -155);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Roller2 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller2, "Round Pizza\nTray Pizza", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 100);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, 304);
    lv_obj_set_y(ui_Roller2, -40);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_DoughBallsTa);

}
